
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/aihuishou
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:com/mybatis/mybatis/com/*.xml
